image:
  name: ctrox/csi-s3:test
  entrypoint: [""]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build

test:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker run --rm --privileged -v $(pwd):$GO_PROJECT_DIR --device /dev/fuse ctrox/$CI_PROJECT_NAME:test
